name: CI

on:
  push:
    branches:
      - "ready/*"

jobs:
  build_and_test:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Compile
        run: mvn install

      - name: Run fast tests
        run: mvn test -DskipTests=false -Dgroups=fast

  automerge:
    runs-on: ubuntu-20.04

    needs:
      - build_and_test
  
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          fetch-depth: 0

      - run: git checkout ${GITHUB_REF#refs/heads/}
      - run: git rebase origin/master
      - run: git branch master
      - run: git push origin master:master
      - run: git push origin :${GITHUB_REF#refs/heads/}

      